### ISSUE TITLE
Sync CLI Tools with App-Backend

### ISSUE THREAD

**Issue by johngriebel** [3Blades/cli-tools#104]
- [x] [Update URL](https://github.com/3Blades/go-sdk/issues/28) paths to include versioning.

**Comment by jgwerner** [comment]
@jkp85 I talked to @johngriebel and we believe that before we add other features we should catch up with CLI Tools. In addition to creating pretty formats for returned results, when listing users and projects `tbs project ls` for example, we should return search results in a pretty table. Ordering, pagination and offset should be user options as its supported by the API.

Send us a proposal for pretty table(s) so we can validate them before implementation. 

3blades/3blades#76

**Comment by johngriebel** [comment]
Removed a couple check list items as it is best to hold off on implementing too many features in go CLI tools before we have made a firm decision on whether or not we are switching to Node. If we decide to implement pretty printing in Go, we should open a new issue. Additionally, we have decided to re-evaluate what it means to integrate search in the CLI tools.
