### ISSUE TITLE
Add commands to manage triggers

### ISSUE THREAD

**Issue by jgwerner** [3Blades/cli-tools#108]
CLI Tools should have commands to manage triggers.

- tbs trigger create
  - cause.id
  - cause.payload
  - cause.method
  - cause.model
  - cause.object_id
  - cause.action_name
  - effect.id
  - effect.payload
  - effect.method
  - effect.model
  - effect.object_id
  - effect.action_name
  - schedule
  - webhook.url
  - webhook.config
- tbs trigger ls
  - limit
  - offset
  - ordering
- tbs trigger update
  - same as create
- tbs trigger replace
  - same as create
- tbs trigger delete
  - trigger id

Examples:

tbs trigger create --cause-action "project-list" --cause-method "get" --effect-method "get" --effect-action "server-list" --webhook-url=<url> --webhook-payload={"text": "Test"}

**Comment by jkp85** [comment]
@johngriebel I agree.

**Comment by johngriebel** [comment]
Closing. A new issue can be opened for any problems found with the new triggers implementation.
