### ISSUE TITLE
create (Create new auto scaling group)

### ISSUE THREAD

**Issue by AbhishikthaReddy** [3Blades/cli-tools#12]
Entity: auto-scaling (Entity to manage servers based on rules), Action: create (Create new auto scaling group)
ARGS: 
--auto-scaling-group-name
--launch-config-name
--schedule-name
[--recurrence ]
[--auto-restart]
[--start-time]
[--end-time]
[--min-size]
[--max-size]
[--desired-capacity]
#55

**Comment by jgwerner** [comment]
Not applicable.
