### ISSUE TITLE
Action: update (updates a auto scale)

### ISSUE THREAD

**Issue by AbhishikthaReddy** [3Blades/cli-tools#14]
Entity: auto-scaling (Entity to manage servers based on rules), Action: update (updates a auto scale) 
ARGS:
--auto-scaling-group-name
--launch-config-name
--schedule-name
[--recurrence ]
[--auto-restart]
[--start-time]
[--end-time]
[--min-size]
[--max-size]
[--desired-capacity]
#55

**Comment by jgwerner** [comment]
Not applicable.
