### ISSUE TITLE
Create a new HTTP server

### ISSUE THREAD

**Issue by AbhishikthaReddy** [3Blades/cli-tools#2]
Description: HTTP server (Model), Command Server (Workspace) or Code Runner (Job), Action: create (Create a new HTTP server) 

ARGS: 
--server-name
--server-type
--resource
--engine
--function-file
--function
--startup-script
[-e] --env-file
#53

**Comment by jkp85** [comment]
@jgwerner How env file should look like? ex:
```
VAR=test
VAR2=test2
```

**Comment by jgwerner** [comment]
No longer supported.
