### ISSUE TITLE
update HTTP Server

### ISSUE THREAD

**Issue by AbhishikthaReddy** [3Blades/cli-tools#4]
Entity: user-server, Description: HTTP server (Model), Command Server (Workspace) or Code Runner (Job), Action: update (updates the HTTP Server) 

ARGS: 
--server-name
--uuid
--server-state
--server-type
--resource
--engine
--function-file
--function
--startup-script
[-e] --env-file
#53

**Comment by jkp85** [comment]
I would create separate commands for start, stop, pause server. I think it's a good idea to follow docker style in this case.
`tbs server start --name=MyServer` is better than `tbs server update --state=start --name=MyServer`

**Comment by raygesualdo** [comment]
@jkp85 Completely agree. State should be a verb after `server`.
