### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by jkp85** [3Blades/cli-tools#48]
3Blades/3blades#12
Large files upload should be handled with features:

- [ ] pause/resume upload
- [ ] upload directory (we can compress dir and decompress on server)
- [x] multi part upload
- [ ] progress bars in ui with speed indicators (similar to docker)

Ideally it should not go through our api server. Direct upload is better if we want to support all of the above.

3blades/3blades#74

**Comment by jgwerner** [comment]
@jkp85 @johngriebel would you agree to add unchecked items as new feature enhancements later? That way we can close this issue and it's upstream epic.

**Comment by johngriebel** [comment]
@jgwerner Yes, I agree.

**Comment by jgwerner** [comment]
Opened as new issues.
