### ISSUE TITLE
delete HTTP Server

### ISSUE THREAD

**Issue by AbhishikthaReddy** [3Blades/cli-tools#5]
Entity: user-server, Description: HTTP server (Model), Command Server (Workspace) or Code Runner (Job), Action: delete (deletes the HTTP Server)

ARGS: 
--server-name
--uuid
--server-state
--server-type
--resource
--engine
--function-file
--function
--startup-script
[-e] --env-file
#53

**Comment by jkp85** [comment]
This is silly, you only need to specify name or id and that should be it.
