### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by jkp85** [3Blades/cli-tools#50]
@jgwerner How do you think trigger command should look like?

Triggers consist of:
- cause (action that trigger needs to be fired after, can be null)
- schedule (cron like schedule to run "1 * * *", can be null)
- effect (action that is fired after cause or schedule, can be null)
- webhook (object with `url` field to send post request after cause or schedule, it can contain optional `config` field to store request payload)

**Comment by jgwerner** [comment]
Will move this general epic to 3blades/3blades repo, we can define specific CLI commands here.

**Comment by jgwerner** [comment]
Closing.
