### ISSUE TITLE
describe HTTP Server

### ISSUE THREAD

**Issue by AbhishikthaReddy** [3Blades/cli-tools#6]
Entity: user-server, Description: HTTP server (Model), Command Server (Workspace) or Code Runner (Job), Action: describe (describes the HTTP Server) 

ARGS:
--server-name
--uuid
#53

**Comment by jkp85** [comment]
I think we should change `--server-name` flag to `--name`.  Also `user-server` should be `server` since we don't have other servers than users. Even if we do then other servers could have a prefix (ex. `admin-server`)

**Comment by jkp85** [comment]
done
