### ISSUE TITLE
Default to unkown user project when listing files

### ISSUE THREAD

**Issue by jgwerner** [3Blades/cli-tools#68]
After logging in (in this case with user foo), and entering the command `tbs file ls` the user receives a message stating:

    Error: There is no project with name: 'titanic'

The only project listed for the `foo` after entering `tbs project ls` user is the `MonaLisa` project. 

The first part of the test, a project namespace was not set with `eval` or in the config file. The `.threeblades.yaml` file only has:

    root:  https://go-pilot.3blades.io

**Comment by jkp85** [comment]
Cannot reproduce. I'm getting
```
Error: Project name is blank. Please set project name with env command.
```
We can default to user project if there is only one.

**Comment by jgwerner** [comment]
Done.
