### ISSUE TITLE
File contents are returned in response schema

### ISSUE THREAD

**Issue by jgwerner** [3Blades/cli-tools#70]
File contents are returned in response schema when using:

    tbs file ls

This particular test had user's namespace/project set with `$eval $(tbs env --namespace foo --project MonaLisa)`. File contents should not be download with `tbs file ls`, only file metadata.

**Comment by jkp85** [comment]
Fixed here https://github.com/jkp85/app-backend/commit/30daa8358dcfb953f9c08f7614b8e56fe271ee7b
