### ISSUE TITLE
File format other than json unclear

### ISSUE THREAD

**Issue by jgwerner** [3Blades/cli-tools#71]
When entering `tbs file ls --format xml` the output upon return lists file xml lines. I am assuming that each one of these lines represents one file. List of lines returned is just the string name. For example the command above returns:

    xml
    xml
    xml
    xml

But it seems to be any string after `--format`. 

In our case, I would suggest disabling the `--format` option unless of course there are other formats that we do support.

**Comment by jkp85** [comment]
@jgwerner Format is similar to docker --format flag for inspect. You can use golang template engine to get what you want. `json` is simply a convenience feature that I implemented to simplify debugging.
