### ISSUE TITLE
Create file with special characters in name and content string leads to unkown error.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/cli-tools#72]
Better indications on how to handle special characters are necessary when creating files with `tbs file create --name "file.txt" --contents "content goes here". 

When slashes are added in the name. It does not state which characters are valid (or invalid), nor specifies what the reason of the error. The test conducted was:

`tbs file create --name "some/path/javier-file.txt" --content "these are the contents of a file. let's add a /n and a /n/r, also a /r."

    Error: unknown error (status 405): {resp:0xc4200ffd40}

User should be instructed in this case to either a) not add special characters or b) escape special characters.

**Comment by jkp85** [comment]
Fixed in https://github.com/jkp85/app-backend/commit/bbf77e3893300be80db21916c0cf5d99299f738a
