### ISSUE TITLE
Update CLI tools with new server states

### ISSUE THREAD

**Issue by jgwerner** [3Blades/cli-tools#97]
Now that we have migrated from Swarm Classic to Swarm Mode, update server states:

- Pending
- Running
- Error

The `Stopped` state no longer exists.

3blades/3blades#60

**Comment by johngriebel** [comment]
@jgwerner Do you mean updating the statuses returned by `tbs server describe --uuid=<server_id>`? If so, this will happen automatically when the relevant changes have been made in app-backend (if they haven't been already). I think the `tbs server` subcommands need updating though, as `tbs server stop` still exists.

**Comment by johngriebel** [comment]
Closing as done.
