### ISSUE TITLE
Add or update user account avatar

### ISSUE THREAD

**Issue by jgwerner** [3Blades/cli-tools#99]
Add option to update avatar or upload a new avatar with `tbs account update ...` option.

We could use a flag such as:

    tbs account update --avatar-image my_image_to_upload.gif

3blades/3blades#84

**Comment by jgwerner** [comment]
Add client side validation, before sending an image file to the backend.

**Comment by raygesualdo** [comment]
What validation are you thinking? File type? File size? Image dimensions?

I think limiting it to `jpg` and `png` with a max file size of `100k` isn't a bad idea (`100k` is Twitter's limit).

**Comment by jgwerner** [comment]
That sounds like a good set of limits to start with.

**Comment by johngriebel** [comment]
@jgwerner @raygesualdo Are we sure it is necessary or wise to implement this in the CLI tools? Since avatars will (presumably) only be seen in the UI anyhow it seems silly to me to add avatars from the command line. Maybe I'm wrong though!

**Comment by raygesualdo** [comment]
Leaving them out makes sense to me. You are correct that the avatar upload feature doesn't make sense in the context of the CLI. Only possible counterargument would be for users that use both the CLI and the UI. But still, they can upload it in the UI. I think we're good without.

**Comment by johngriebel** [comment]
@raygesualdo Thanks. Going to close now.
